### ISSUE TITLE
Remove "International Conference on " part from title

### ISSUE THREAD

**Issue by HKervadec** [MIDL-Conference/midl-website#12]
Per @bramvanginneken e-mail, it seems that the MIDL board wishes to refer to the conference only as "Medical Imaging with Deep Learning". While this is a quick update, it should be coordinated across all midl websites (`midl.io`, `{2018,2019,2020,2021}.midl.io`). 

Most of the updates are for the title on the main page, and sometimes small references inside the website (in the call for paper in the 2020 edition for instance). 

![Screenshot_2020-02-03 MIDL 2020](https://user-images.githubusercontent.com/4191866/73660780-c6a29480-4690-11ea-88ac-fc6effcdf21c.png)

I am willing to create pull requests for all websites, once this decision is confirmed.

**Comment by nlessmann** [comment]
Hi Hoel, could you implement this on the 2020 website? I will take care of the other websites and will adjust the template and theme. Thanks for the offer to prepare pull requests, but this is luckily not much work so that's not needed.

**Comment by HKervadec** [comment]
Yeah, I will do it ; but did you had a confirmation from Bram ? His wording was not completely clear that the MIDL board had come to a decision. To quote him:
> I think we should also remove “International conference on” from all the websites as people will otherwise use that as the name of the conference in references. We’ll discuss this in the board.

**Comment by nlessmann** [comment]
Yes, it's confirmed, I spoke with him 5 min ago

**Comment by HKervadec** [comment]
Implemented in https://github.com/MIDL-Conference/midl-website-2020/commit/e0c017360cba54c358e554d5a31bbc5c870fcf10

Notice that I modified the call for paper this way:
https://github.com/MIDL-Conference/midl-website-2020/commit/e0c017360cba54c358e554d5a31bbc5c870fcf10#diff-52f92173c1e872c096f97b9cc087d7e2R11

> for the 3rd International Conference on Medical Imaging with Deep Learning.

became 
>for the 3rd **edition** of Medical Imaging with Deep Learning.`

Alternative updates:
* for the 3rd Medical Imaging with Deep Learning
* for Medical Imaging with Deep Learning

**Comment by nlessmann** [comment]
Thanks, I will refresh the theme and then we should be done

**Comment by HKervadec** [comment]
Also updated the Twitter account. I am letting know the organizers of current year.

**Comment by nlessmann** [comment]
Great! On Twitter, the text in the banner is still the old one:

![image](https://user-images.githubusercontent.com/773597/74041929-e5719580-49c6-11ea-826e-e4be5b49fd10.png)

**Comment by HKervadec** [comment]
Yes I noticed just after posting that. I am coordinating with Tess to update it, as it is her creation

**Comment by HKervadec** [comment]
I just updated the banner, I think we covered almost everything.
I'll make sure the other support material that we have are updated (that includes the document sent to prospective sponsors).
